apiVersion: v1
kind: Service
metadata:
  name: arachni
  labels:
    name: arachni-service
    app: archerysec-app
spec:
  ports:
    - port: 7331
      targetPort: 7331
  selector:
    name: arachni-application
    app: arachni-app