apiVersion: apps/v1
kind: Deployment
metadata:
  name: arachni-deployment
  labels:
    app: archerysec-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: arachni-application
      app: arachni-app
  template:
    metadata:
      name: arachni-application
      labels:
        name: arachni-application
        app: arachni-app
    spec:
      containers:
        - name: arachni
          image: ahannigan/docker-arachni
          resources:
            requests:
              memory: "1024Mi"
            limits:
              memory: "2000Mi"
          command: ["bin/arachni_rest_server"]
          args: ["--address", "0.0.0.0"]
          ports:
            - containerPort: 7331