apiVersion: v1
kind: Service
metadata:
  name: archerysec-app
  labels:
    name: archerysec-application
    app: archerysec-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30008
  selector:
    name: archerysec-application
    app: archerysec-app