apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvas-deployment
  labels:
    app: archerysec-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openvas-application
      app: openvas-app
  template:
    metadata:
      name: openvas-application
      labels:
        name: openvas-application
        app: openvas-app
    spec:
      containers:
        - name: openvas
          image: avhost/docker-openvas
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "1000Mi"
          ports:
            - containerPort: 9390