apiVersion: v1
kind: Service
metadata:
  name: zaproxy
  labels:
    name: zap-service
    app: archerysec-app
spec:
  ports:
    - port: 8090
      targetPort: 8090
  selector:
    name: zap-application
    app: zap-app